import type { Metadata } from "next";
import { Emilys_Candy, Geist, Geist_Mono, Nanum_Pen_Script } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nanumPenScript = Nanum_Pen_Script({
  variable: "--font-nanum-pen",
  weight: "400",
  subsets: ["latin"],
});

const emilysCandy = Emilys_Candy({
	variable: "--font-emilys-candy",
	weight: "400",
	subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
  		className={`${geistSans.variable} ${geistMono.variable} ${nanumPenScript.variable} ${emilysCandy.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
			<Analytics />
      </body>
    </html>
  );
}
